services:
  - type: web
    name: controle-estoque-reposicao
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"

